os: linux
dist: xenial

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  DOCKER_COMPOSE_VERSION: 1.25.5
  NODE_PATH: /home/travis/build/AndreasRoither/Snippets/ElectronApp/Snippets/node_modules

git:
  depth: false

branches:
  only:
    - master

stages:
  - sonarcloud
  - build docker
  - build electron
  - test rest api

jobs:
  include:
    - stage: sonarcloud
      name: "Sonarcloud code analysis"
      addons:
        sonarcloud:
          organization: "andreasroither" # the key of the org you chose at step #3
          token: $SONAR_TOKEN # encrypted value of your token
      language: node_js
      node_js: 13
      script:
        - cd ./ElectronApp/Snippets/
        - npm install
        - cd ..
        - cd ..
        - sonar-scanner
    - stage: build docker
      name: "Build docker images with tag and push to dockerhub/heroku deploy"
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - cd ./Docker/
        - docker-compose up -d
        - docker images
        - GIT_SHA="$(git rev-parse --short HEAD)"
        - docker tag dpage/pgadmin4:latest andreasroither/snippets_pgadmin:latest
        - docker tag dpage/pgadmin4:latest andreasroither/snippets_pgadmin:$GIT_SHA
        - docker tag snippets_restapi:latest andreasroither/snippets_restapi:latest
        - docker tag snippets_restapi:latest andreasroither/snippets_restapi:$GIT_SHA
        - docker tag snippets_db:latest andreasroither/snippets_db:latest
        - docker tag snippets_db:latest andreasroither/snippets_db:$GIT_SHA
        - docker push $DOCKER_USERNAME/snippets_pgadmin:latest
        - docker push $DOCKER_USERNAME/snippets_pgadmin:$GIT_SHA
        - docker push $DOCKER_USERNAME/snippets_restapi:latest
        - docker push $DOCKER_USERNAME/snippets_restapi:$GIT_SHA
        - docker push $DOCKER_USERNAME/snippets_db:latest
        - docker push $DOCKER_USERNAME/snippets_db:$GIT_SHA
      deploy:
        app: $HEROKU_APP_NAME
        provider: heroku
        skip_cleanup: true
        api_key: $HEROKU_AUTH_TOKEN
    - stage: build electron
      name: "Make electron app"
      os: windows
      language: node_js
      node_js: 13
      script:
        - cd ./ElectronApp/Snippets/
        - npm install
        - npm run make
    - stage: test rest api
      name: "Unit test Go RestAPI"
      language: go
      go: 1.14.x
      services:
        - docker
      script:
        - docker run $DOCKER_USERNAME/snippets_db:latest
        - cd ./GoRestAPI/
        - go test -v
