# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- azure-app

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: ''
  imageRepository: ''
  containerRegistry: ''
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: QA
    displayName: QA
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: ''
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: ''
        cliProjectName: 'Snippets'
        cliSources: './GoRestAPI/'
    - task: SonarCloudAnalyze@1
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: ''
        azureContainerRegistry: '{"loginServer":"", "id" : ""}'
        dockerComposeFile: '**/docker-compose_azure.yml'
        dockerComposeFileArgs: ''
        action: 'Build services'
        additionalImageTags: '$(Build.BuildId)'
        includeSourceTags: true
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: ''
        azureContainerRegistry: '{"loginServer":"", "id" : ""}'
        dockerComposeFile: '**/docker-compose_azure.yml'
        dockerComposeFileArgs: ''
        action: 'Push services'
        additionalImageTags: '$(Build.BuildId)'
        includeSourceTags: true