version: "3.5"

# Create a local data volume since windows and linux postgresql file systems
# won't work together... on linux use a normal volume ./data
# docker volume create --name data -d local

services:
  db:
    build: ./postgres/
    container_name: snippets_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - postgres:/data/postgres

  pgadmin:
    container_name: snippet_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db

networks:
  postgres:
    driver: bridge

# comment out if normal os volumes are used
volumes:
  postgres:
  pgadmin:
